In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

boston = datasets.load_boston()
boston

{'DESCR': "Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per

In [ ]:
train_data_bs, test_data_bs, train_labels_bs, test_labels_bs = train_test_split(boston.data, boston.target, test_size=0.2)
train_data_bs

In [3]:
test_data_bs

array([[  2.44953000e+00,   0.00000000e+00,   1.95800000e+01, ...,
          1.47000000e+01,   3.30040000e+02,   1.13200000e+01],
       [  1.35222000e+01,   0.00000000e+00,   1.81000000e+01, ...,
          2.02000000e+01,   1.31420000e+02,   1.33300000e+01],
       [  8.71675000e+00,   0.00000000e+00,   1.81000000e+01, ...,
          2.02000000e+01,   3.91980000e+02,   1.71200000e+01],
       ..., 
       [  1.52880000e+01,   0.00000000e+00,   1.81000000e+01, ...,
          2.02000000e+01,   3.63020000e+02,   2.32400000e+01],
       [  3.22640000e-01,   0.00000000e+00,   2.18900000e+01, ...,
          2.12000000e+01,   3.78250000e+02,   1.69000000e+01],
       [  1.42362000e+01,   0.00000000e+00,   1.81000000e+01, ...,
          2.02000000e+01,   3.96900000e+02,   2.03200000e+01]])

In [4]:
train_labels_bs

array([ 21.9,  31.5,  12.7,  15.7,  22.9,  13.1,  28.4,   8.7,  29. ,
        21.2,  35.1,  23. ,   7.4,  42.8,  32.5,  30.5,  22.7,  19.5,
         8.5,  17.8,  32.7,  34.7,  22.9,  11.8,  14.9,  21.7,  21.2,
         8.4,  12.6,  10.8,  29. ,  24.8,  28.7,  19.1,  50. ,  33.2,
        19.2,  18.9,  22.2,  22. ,  21.7,  20.2,  34.9,  27.5,  22.4,
        15. ,  15.2,  14.6,  23.3,  19.5,  24.4,  18.5,  21.8,  21.4,
        25.1,  50. ,  23.2,  25. ,  21.4,  19.3,  23.9,   5. ,  16.5,
        13.8,  23.8,  23.7,  21.2,  15.4,  14.3,  17.8,  10.2,  17.5,
        15.6,   5.6,  14.1,   8.3,  17.7,   5. ,  33.1,  20.6,  18.5,
        23.1,  13.9,  17.4,  50. ,  27. ,  25. ,  50. ,  41.7,  10.5,
        23.1,  50. ,  24.1,  22.6,  20.1,  23.7,  38.7,  45.4,  33.4,
        19.7,  23.1,  20.8,  12.3,  19.2,  17.8,  14.5,  21. ,  23.1,
        26.6,  19.6,  33.2,  21.2,  23. ,  50. ,   7.2,  24.4,  19.8,
        17.5,  32.2,  13.4,  25.2,  17.2,  25. ,  21.8,  14.8,  23.4,
        18.6,  20.2,

In [5]:
test_labels_bs

array([ 22.3,  23.1,  13.1,  21.4,  19.4,  24.8,  23.9,  16.5,  36.1,
        23.8,  30.1,  28.5,  10.2,  22.3,  17.1,  20.8,  22.7,  25. ,
        22.2,  12.7,  14.2,  22.9,  50. ,   9.7,  33.8,  21.6,  18.5,
        25. ,  50. ,  22.6,  43.8,  29.1,  31.5,  35.4,  36.2,  20.6,
        21.1,  16.2,  10.2,  42.3,  24.8,  12.1,  11. ,  37. ,   7. ,
        20. ,  20.6,  23.8,  20.4,  11.7,  22.6,  21.7,  50. ,  37.3,
        23.9,  23.2,  19.3,  37.9,  24.6,  21.2,  21.4,  20.8,  15.6,
        22. ,  28.7,  22. ,  50. ,  28. ,  14.9,  13.3,  22.4,  31.6,
        22. ,  21.4,  14.5,  39.8,  19.5,  20.3,  28.7,  25. ,  20.6,
        36.4,  19. ,  26.4,  18.2,  19.7,  18.7,  14.4,  24.4,  33.1,
        30.3,  12. ,  24.2,  22. ,  19.3,  19.6,  14.3,  19.9,  19.9,
        13.9,  17.4,   7.2])

In [8]:
forest = RandomForestRegressor()
forest.fit(train_data_bs, train_labels_bs)

train_labels_pred = forest.predict(train_data_bs)
test_labels_pred = forest.predict(test_data_bs)
train_labels_pred

array([ 22.14,  30.99,  12.78,  16.2 ,  22.86,  13.81,  27.61,   9.1 ,
        28.17,  21.19,  33.81,  22.4 ,   8.48,  40.92,  31.9 ,  29.79,
        22.33,  20.27,   8.2 ,  16.4 ,  32.92,  35.42,  22.12,  12.04,
        15.31,  20.76,  22.1 ,  10.64,  13.82,  10.35,  30.54,  24.06,
        28.67,  17.52,  48.76,  33.47,  19.67,  19.47,  22.81,  22.9 ,
        22.04,  20.32,  31.95,  22.51,  23.11,  20.16,  15.84,  14.75,
        22.98,  18.99,  25.45,  20.04,  21.57,  21.11,  25.58,  46.05,
        20.43,  26.42,  21.52,  19.33,  23.91,   6.66,  17.71,  15.68,
        23.7 ,  23.71,  21.1 ,  14.82,  14.2 ,  18.74,   9.3 ,  17.81,
        15.85,   8.68,  14.27,   8.62,  18.06,   6.31,  32.17,  21.1 ,
        19.18,  23.35,  15.75,  18.86,  49.88,  25.85,  24.48,  46.26,
        44.39,  10.32,  21.99,  48.34,  24.1 ,  23.23,  20.36,  23.64,
        40.71,  46.21,  31.69,  20.05,  22.93,  20.78,  11.86,  18.98,
        16.25,  14.31,  20.55,  21.9 ,  26.6 ,  19.8 ,  34.98,  21.63,
      

In [9]:
test_labels_pred

array([ 22.86,  17.25,  15.32,  21.63,  16.78,  23.3 ,  26.85,  22.76,
        35.41,  23.23,  31.87,  30.35,  12.02,  23.2 ,  18.53,  21.92,
        21.18,  24.8 ,  22.11,  10.96,  16.37,  23.76,  45.78,   9.62,
        31.59,  21.66,  19.28,  23.84,  31.53,  20.34,  41.35,  23.85,
        35.21,  34.68,  26.93,  21.07,  20.55,  16.32,  15.95,  43.18,
        29.98,  12.18,  14.14,  31.86,  12.74,  17.26,  20.49,  24.06,
        20.25,  15.09,  20.62,  20.05,  38.55,  34.56,  22.05,  22.21,
        20.36,  35.27,  24.23,  22.5 ,  21.84,  20.15,  12.98,  23.94,
        24.83,  20.44,  40.07,  26.6 ,  15.36,  12.82,  21.19,  33.42,
        22.85,  18.69,  13.93,  37.63,  18.48,  21.45,  24.1 ,  23.02,
        18.06,  35.66,  21.69,  22.7 ,  19.2 ,  21.84,  20.99,  14.54,
        23.69,  31.92,  32.31,  12.7 ,  23.35,  27.63,  19.58,  19.19,
        15.37,  20.26,  19.69,  12.36,  16.47,   9.72])

In [12]:
plt.figure(figsize=(20,10))
plt.plot(test_labels_bs,label="True")
plt.plot(test_labels_pred, label="predicted")
